### ISSUE TITLE
Bug Scrub meeting concept - volunteer organizing

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/community#101]
I've floated the idea in the most recent FluxCD community meeting of a new "Bug Scrub" meeting with a similar structure to SIG-CLI's meeting of the same name, either in one of the existing weekly meeting timeslots to replace an existing meeting on the calendar, or at a new time about once a month. RFC ❓ 

Edit: for visibility, the meeting is scheduled at **Wednesday June 30 at 8:00 ET/12:00 UTC**

https://github.com/kubernetes/community/blob/master/sig-cli/README.md#meetings – the goal would be to visit every issue in every repo, (or pick one repo for the first try) check labels and make a decision about whether there are any mis-applied or missing labels that could be updated on the issue; optionally make an assignment of the issue to whoever has volunteered to follow it up, and close issues that are stale or drive-by with no response for a while, or otherwise look like they can be closed.

The maintainers will of course be welcome at this meeting, but their presence should not be required every time thanks to #75; we only need one person with Triage role present at the meeting to enable us to make a difference in the queues, if there is one person in attendance who can update labels, great; more than one, (we can try divide and conquer as we maybe find out that it is impossible to visit all the issues in every repo in an hour.)

If the meeting time does not work for everyone, there would be nothing stopping us from having more than one Bug Scrub meeting every month, with different hosts in different time zones, but for now I am just proposing one monthly meeting, and looking for opinions about what timing would be good for interested volunteers. 👍 If anyone has been to sig-cli bug scrubs, love to hear how it works. (The SIG-CLI bug scrub meetings are recorded for posterity and we can review their specific implementation, or just try out our own and shoot from the hip, no need to make this research project harder than needed.)

This meeting idea is simply to address issue queue hygiene and clean it up quickly, this is not meant to be a full queue review or spend time responding to support requests other than to label them properly; but before #75 we could probably not have done Bug Scrub meetings effectively without a maintainer present. It is not a meeting to discuss the outcome or resolution of complex topics, we can spend 2-5 minutes maximum on each issue to have a chance at actually getting through all issues (even if there are multiple members present with the triage role, and if we took the approach of divide and conquer multi-threaded without actually talking about each issue, it will be hard to get through even 50% of open issues, I am sure of this!)

**Comment by kingdonb** [comment]
Turns out that SIG Node is having a bug scrub event in a week or two that we can use to inform our meeting structure:

https://hackmd.io/@sig-node-bug-scrub/S1gQnDbjO

They are doing a two day globally asynchronous bug scrub event, I am not that ambitious, but it looks like they have already developed a structure for distributing the workload among dozens or hundreds of participants, so if we ever get dozens or hundreds of participants for our event (I'm expecting like 2-5 people will attend at first) we can borrow or implement from parts of their structure.

I'd like to hold the first Flux bug scrub before then, since I already have a structure in mind and it is suitable for 2-5 people, if that's how many we get. There is a note in Slack channel here: https://cloud-native.slack.com/archives/C01A402P0R2/p1623943278250100 please respond on that thread, or in this issue, if you are interested in volunteering, and I'll make sure you get notified when there is a Doodle poll to help us decide and set the timing.

**Comment by kingdonb** [comment]
Wednesday June 30 at 8:00 ET/12:00 UTC - we discussed this in the community meeting for Flux today, and we have set a time and date for our first iteration on this meeting.

The community meeting has this alternating-weeks schedule with Early and Late meetings. This time was picked as it is the same time of the week that our Flux Community "Early" meeting would be scheduled at, but it is an off-week when the Flux "Late" meeting is the one on the calendar.

(We hope this time works for everyone but inevitably it won't work for everyone) @alisondy @scottrigby want to know if this meeting time will work for you next week, as I know you were interested.

If someone can't make it and still wanted to participate, you can; I use a spreadsheet-driven process, and there's nothing stopping individuals who were or weren't in attendance from picking up where we left off between scheduled meetings. This is an iterative process and we will do it more, (maybe once a month, maybe more often.) The artifacts will all be published, (I'll post them here for starters, until we have some better established process and really can say we know what we're doing.)

I will try to bring with updates to make my process work with multiple repos from FluxCD. Right now I am generating these spreadsheets about once a week for the `f/flux` repo, old versions are helpful for reference to see how much we are moving the high-water mark from week to week (and how much it is just moving with the tides as new reports and PRs come in.)

Please join us! We hope this new meeting is valuable to our community and will help us move some issues forward and get more eyes on PRs. 👍

**Comment by kingdonb** [comment]
The bug scrub is on!

Please visit #flux and join us now

**Comment by mewzherder** [comment]
Where do we go to find out dates for future bug scrubs? thx. :)

**Comment by makkes** [comment]
@mewzherder yesterday's meeting is on the [flux-dev calendar](https://lists.cncf.io/g/cncf-flux-dev/calendar) and I suppose the next ones will land there, too.

**Comment by kingdonb** [comment]
@mewzherder @makkes That's correct, I've just added the next two to the CNCF calendar. (Thanks @dholbach for getting me the access needed to keep this schedule published.)

July 14 - 8:00 AM ET / 12:00 PM UTC
July 22 - 1:00 PM ET / 17:00 PM UTC

Note that the July 22 event has moved from the originally scheduled timing because of a standing conflict on our internal calendar.

**Comment by kingdonb** [comment]
In case this timing does not work for anyone, I am open to creating a poll and planning for different time zones, (and as the process solidifies over time, and we get better at pulling in volunteers, so more people are onboarded to understand how this is done, I don't necessarily have to be the host of this event every single time. I'm building some glue code to facilitate streamlining of the Bug Scrub spreadsheet artifact generation process.)

Meanwhile, until we've established a schedule and found it works to get the most volunteers in attendance, I will try to at least make sure the next Bug Scrub always goes on the calendar by... *checks watch* the day after the previous bug scrub.

I use Google Calendar, and the ics calendar file subscriptions, (which is the [recommended way to keep yourself informed](https://fluxcd.io/community/#subscribing-to-the-flux-dev-calendar) about the CNCF Flux Dev meeting schedule), and it is frankly not very good when it comes to pushing out updates to the schedule, unless I'm somehow not using it correctly.

We updated the CNCF calendar more than 24 hours before this event, and I watched and waited as an experiment to see how long it would take Google to update the calendar subscription to match the published `.ics` file – I did not see any updates reflected on my Google calendar for over 24 hours. I finally deleted my local calendar subscription and recreated it to be able to see the change. It is supposed to update, all indications point to Google simply not having made this feature very good; I found forum threads that said you should expect to wait 18-24 hours for updates to be reflected. 😕

**Comment by makkes** [comment]
I ran across the same issue with my Google calendar not showing the event for hours even though I saw it on the website I linked above. It's unfortunate. But eventually it turned up.

**Comment by kingdonb** [comment]
The calendar has been updated with some recurring events so it should be easier to follow our schedule now.

I am thinking about building a mailing list, but as a starting point I've added a worksheet for attendance and a section for meeting minutes to the weekly Flux Bug Scrub spreadsheet.

People can add their e-mail addresses to the spreadsheet when they attend, or what I don't know, still not sure if a mailing list is the best format to communicate with the group. It is certainly confounded a bit by summer schedules, as I know many people are on vacations right now.

We are hoping to build up a strong base of repeat attendees; so far most visitors have only joined once, but I'm not reading too much into that as we have a sample size of 4 meetings across one month.

Other planned enhancements: we would like to have a meeting time where we do "FAQ scrub" or "Discussions scrub" though this does not yet fit into the current structure based on spreadsheets, it is something we'd like to target too.

We've also had a problem that when we tweet, we need to send a link, and the blog links that include the date of the next bug scrub can only be used once.

So I'm aiming to put out another blog post about the bug scrub, perhaps this week, so that we have something to tweet out which does not need to be updated – I'm thinking if possible it should either include some kind of procedure/javascript widget that points at the next bug scrub based on reading the date from the Flux Dev calendar, or maybe easier just defer and provide a link to the calendar and let attendees check about the date.

**Comment by dholbach** [comment]
Shall we maybe just add a "team section" to https://github.com/fluxcd/community/blob/main/COMMUNITY.md?

**Comment by kingdonb** [comment]
The "Bug Scrub" formal process is "in flux" (...loud guffawing) as the formal process has been scrapped and is being rewritten. This shouldn't take very long.

Flux Bug Scrub attendance goes in fits and starts, we're hoping to get some new recruits again very soon! Bug Scrubs are every week, until the holiday, then starting up again.

The best place to find out about the most current Bug Scrub meet-up timing and other details is at fluxcd.io/#calendar

It's not completely obvious on mobile, but if you hover your mouse an animation is meant to show that you can

**Click to find the Zoom** / calendar details:

<img width="494" alt="Screen Shot 2021-12-08 at 7 55 01 PM" src="https://user-images.githubusercontent.com/3286998/145314874-eedf98d1-a1f0-4606-8bac-cb34dcd18c0d.png">

I also try to remind everyone about subscribing to the [Flux Dev Calendar](https://fluxcd.io/community/#subscribing-to-the-flux-dev-calendar) which makes sure you get the detail in your local time zone, and to set up Google calendar reminders.

There is a bi-weekly scheduling plan which is meant to provide times accessible to folks in EMEA as well as North America

**Comment by kingdonb** [comment]
We've added Flux Bug Scrub AEST, which better caters to folks in Australia and Asia (we hope!)

Closing this, come join us at Bug Scrub if you want to volunteer!
