### ISSUE TITLE
List Flux events in CNCF Public Events calendar

### ISSUE THREAD

**Issue by scottrigby** [fluxcd/community#11]
I wanted to join a CNCF slack SIG Contributor Strategy meeting and just happened to notice that some projects use their `lists.cncf.io` group calendar, while others list on the CNCF Public Events calendar https://www.cncf.io/calendar/. 

That SIG also has their events listed in their `lists.cncf.io` group calendar, but it's out of date. In the CNCF `#sig-contributor-strategy` channel I was told the CNCF Public Events calendar is the source of truth.

Because of that, and also for greater visibility to potential new contributors, perhaps we should request to list Flux events on the CNCF Public Events calendar as well.

**Comment by dholbach** [comment]
AFAICS this is now done? https://www.cncf.io/calendar/

**Comment by scottrigby** [comment]
Yes ✅
