### ISSUE TITLE
Document who is maintainer

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#120]
GH Action to crawl
- API equivalent of https://github.com/orgs/fluxcd/teams/maintainers/members and create a file that can be read by everyone
- (maybe) all MAINTAINERS files across fluxcd and create overview of who maintains what
- also who's steering committee

**Comment by kingdonb** [comment]
I have a GitHub GraphQL api client as part of the Bug Scrub effort, I may be able to help with this.

(Many of GitHub's newer APIs are not exposed anymore to the world except via GraphQL.)

**Comment by dholbach** [comment]
Superseded by #135
