### ISSUE TITLE
fluxcd-community/helm-charts via artifacthub in fluxcd org

### ISSUE THREAD

**Issue by haarchri** [fluxcd/community#132]
we published helm-charts for https://github.com/fluxcd-community/helm-charts via https://github.com/fluxcd-community/helm-charts/issues/5

**artifacthub:**
https://artifacthub.io/packages/helm/fluxcd-community/flux2

is it possible to move the artifactoryhub to fluxcd org? who is the right person to talk ?

thanks

**Comment by hiddeco** [comment]
Given the `fluxcd-community` GitHub organization is separated to distinguish "neutral endorsement" from "adoption under official organization", I think the same should be done for any ArtifactHub (or other) solution.

I have just created this organization and invited you, which should allow you to transfer the ownership of the repository to the organization.

**Comment by haarchri** [comment]
Thanks - done https://artifacthub.io/packages/helm/fluxcd-community/flux2
