### ISSUE TITLE
Enforce DCO commit sign-off on all repositories

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/community#17]
Given we are wrapping up #1, and have already agreed on requiring a sign-off on commits, we should bring a check in place to enforce this. The easiest way of doing this is to make use of the [Probot: DCO](https://github.com/probot/dco) GitHub action, and [require the status check to pass before merge](https://github.com/probot/dco/blob/master/docs/required-statuses.md).

High priority:

- [x] [fluxcd/toolkit](https://github.com/fluxcd/toolkit)
- [x] [fluxcd/source-controller](https://github.com/fluxcd/source-controller)
- [x] [fluxcd/kustomize-controller](https://github.com/fluxcd/kustomize-controller)
- [x] [fluxcd/helm-controller](https://github.com/fluxcd/helm-controller)
- [x] [fluxcd/notification-controller](https://github.com/fluxcd/notification-controller)
- [x] [fluxcd/image-reflector-controller](https://github.com/fluxcd/image-reflector-controller)
- [x] [fluxcd/image-automation-controller](https://github.com/fluxcd/image-automation-controller)
- [x] [fluxcd/community](https://github.com/fluxcd/community)
- [x] [fluxcd/pkg](https://github.com/fluxcd/pkg)

Repositories not listed here have lower priority, but must be taken care of.

- [x] [fluxcd/flux](https://github.com/fluxcd/flux)
- [x] [fluxcd/website](https://github.com/fluxcd/website)

**Comment by hiddeco** [comment]
The bot has been installed and enabled for the overall organization, requiring the status check to pass is only possible when it has run at least once for a repository, which is a matter of time.

**Comment by scottrigby** [comment]
The changes for end users are outlined in this PR description https://github.com/fluxcd/community/pull/13

**Comment by scottrigby** [comment]
This is now outlined in https://github.com/fluxcd/community/blob/main/CONTRIBUTING.md. The info was also sent to the flux-dev mailing list. I think we're good to close this one ✅
