### ISSUE TITLE
REQUEST: New membership for @pjbgf

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/community#175]
### GitHub Username
@pjbgf

### Requirements
- [x] I have reviewed the community membership guidelines in `community-roles.md`
- [x] I have subscribed to the cncf-flux-dev e-mail list [https://lists.cncf.io/g/cncf-flux-dev/join](https://lists.cncf.io/g/cncf-flux-dev/join)
- [x] I am actively contributing to 1 or more `fluxcd` GitHub org repos (eg. Flux, Flagger)
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @stefanprodan
- @relu 

### List of contributions to the Flux project
- PRs reviewed / authored:
  - https://github.com/fluxcd/golang-with-libgit2/pull/14
  - https://github.com/fluxcd/image-automation-controller/pull/317
  - https://github.com/fluxcd/source-controller/pull/580
  - https://github.com/fluxcd/source-controller/pull/574
  - https://github.com/fluxcd/source-controller/pull/577
  - https://github.com/fluxcd/helm-controller/pull/396
  - https://github.com/fluxcd/source-controller/pull/572
  - https://github.com/fluxcd/source-controller/pull/573
  - https://github.com/fluxcd/kustomize-controller/pull/536
  - https://github.com/fluxcd/source-controller/pull/558
  - https://github.com/fluxcd/image-automation-controller/pull/303
  - https://github.com/fluxcd/notification-controller/pull/306
  - https://github.com/fluxcd/flux2/pull/2316
  - https://github.com/fluxcd/pkg/pull/218
  - https://github.com/fluxcd/pkg/pull/212
  - https://github.com/fluxcd/community/pull/167
  - https://github.com/fluxcd/kustomize-controller/pull/522
  - https://github.com/fluxcd/helm-controller/pull/386
  - https://github.com/fluxcd/source-controller/pull/521
  - https://github.com/fluxcd/source-controller/pull/505
  - https://github.com/fluxcd/image-automation-controller/pull/283
- Discussions involved in & Issues responded to:
  - https://github.com/fluxcd/pkg/issues/174
  - https://github.com/fluxcd/flux2/issues/2014
  - https://github.com/fluxcd/pkg/issues/172
- Flux subprojects I am involved with:
  - Flux
  - Controllers
  - golang-with-libgit2

**Comment by stefanprodan** [comment]
+1 from me as member of the @fluxcd/oversight-committee 

Thanks @pjbgf for all the hard work on making Flux more secure 🏅

**Comment by makkes** [comment]
+1 Thanks @pjbgf for all the fuzzing work!

**Comment by squaremo** [comment]
+1, definitely 🌟

**Comment by relu** [comment]
+1 from me as a member of @fluxcd/maintainers

Keep on rocking, @pjbgf!

**Comment by kingdonb** [comment]
Big +1 from me! 💥

**Comment by darkowlzz** [comment]
+1 from me too
