### ISSUE TITLE
Please create fluxcd/stats repository

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#181]
@kingdonb and I talked about how to resolve fluxcd/website#803 

Thinking was that it might be most secure, if we write the data to a separate repository?

We might as well start changing https://github.com/fluxcd/community/blob/main/.github/workflows/repostats.yaml to write to that repository as well.

Do you @fluxcd/maintainers have any thoughts on this?

**Comment by stefanprodan** [comment]
Here it is https://github.com/fluxcd/stats

**Comment by dholbach** [comment]
Thanks a lot @stefanprodan
