### ISSUE TITLE
REQUEST: New membership for @aryan9600

### ISSUE THREAD

**Issue by aryan9600** [fluxcd/community#184]
### GitHub Username
@aryan9600

### Requirements
- [x] I have reviewed the community membership guidelines in `community-roles.md`
- [x] I have subscribed to the cncf-flux-dev e-mail list [https://lists.cncf.io/g/cncf-flux-dev/join](https://lists.cncf.io/g/cncf-flux-dev/join)
- [x] I am actively contributing to 1 or more `fluxcd` GitHub org repos (eg. Flux, Flagger)
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @stefanprodan 
- @hiddeco 

### List of contributions to the Flux project
- PRs reviewed / authored:
  - https://github.com/fluxcd/source-controller/pull/515
  - https://github.com/fluxcd/notification-controller/pull/307
  - https://github.com/fluxcd/kustomize-controller/pull/539
  - https://github.com/fluxcd/source-watcher/pull/26
  - https://github.com/fluxcd/image-automation-controller/pull/299
  -  https://github.com/fluxcd/flagger/pull/1093
  - https://github.com/fluxcd/image-automation-controller/pull/311
  - https://github.com/fluxcd/image-automation-controller/pull/314
  - https://github.com/fluxcd/flagger/pull/1108
  - https://github.com/fluxcd/image-reflector-controller/pull/232
  - https://github.com/fluxcd/pkg/pull/248
  - https://github.com/fluxcd/flagger/pull/1125
  - https://github.com/fluxcd/flagger/pull/1128
  - https://github.com/fluxcd/flagger/pull/1130

- Discussions involved in & Issues responded to
  - https://github.com/fluxcd/flagger/issues/1126
  - https://github.com/fluxcd/flux2/issues/2273
  - https://github.com/fluxcd/image-automation-controller/issues/316
  
- Flux subprojects I am involved with (Flagger, Flux, Controllers)
  - flux
  - controllers
  -  flagger

**Comment by hiddeco** [comment]
+1 without any doubt.

**Comment by dholbach** [comment]
Not to forget https://github.com/fluxcd/website/pull/827 - thanks for the collaboration on this!

+1 from me too!

**Comment by stefanprodan** [comment]
+1 Thanks Sanskar for all your contributions 🏅

**Comment by hiddeco** [comment]
Having your sponsors confirm is sufficient, and you should have an invite @aryan9600. Accepting this should also allow you to close this PR yourself :-)
