### ISSUE TITLE
REQUEST: New membership for arhell

### ISSUE THREAD

**Issue by Arhell** [fluxcd/community#202]
### GitHub Username

@arhell

### Sponsors

@dholbach
@stefanprodan

#### issue:
https://github.com/fluxcd/website/issues?q=is%3Aissue+author%3AArhell

#### PRs:

https://github.com/fluxcd/website/pulls?q=is%3Apr+author%3AArhell

**Comment by dholbach** [comment]
Sorry for not following up to this issue. I'll reopen it.

Stefan and I had followed up with @Arhell independently over email. Back when the application came in we felt that other folks who had applied for project member status had contributed bigger pieces of work and wondered if we could collaborate on e.g. fluxcd/website#784 and afterwards sponsor the application.

We very much appreciate your work and feel like many issues e.g. on mobile are fixed now, which gives the site a more mature feel. Thanks a lot for being involved in the project!

**Comment by dholbach** [comment]
I am happy to sponsor @Arhell 's application for membership at this point. Since April we have seen many improvements across the board for the website, especially UX issues and with particular on mobile: https://github.com/fluxcd/website/commits?author=Arhell

Thanks a lot for helping us deliver a nicer website and docs to our users!

**Comment by squaremo** [comment]
I will endorse @Arhell for membership too -- I see lots of helpful contributions and a commitment to the project 🙏 🌟

**Comment by dholbach** [comment]
@Arhell Can you please confirm you have done the following from [this document](https://github.com/fluxcd/community/blob/main/PROCESS.md#applying-for-flux-membership)?

I think it should just be points 1), 2), 4) the other ones are fine.

### Requirements
- [ ] I have reviewed the community membership guidelines in [`community-roles.md`](https://github.com/fluxcd/community/blob/main/community-roles.md#community-member)
- [ ] I have subscribed to the cncf-flux-dev e-mail list [https://lists.cncf.io/g/cncf-flux-dev/join](https://lists.cncf.io/g/cncf-flux-dev/join)
- [ ] I am actively contributing to 1 or more `fluxcd` GitHub org repos (eg. Flux, Flagger)
- [ ] I have enabled 2FA in GitHub
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Comment by Arhell** [comment]
> @Arhell Can you please confirm you have done the following from [this document](https://github.com/fluxcd/community/blob/main/PROCESS.md#applying-for-flux-membership)?
> 
> I think it should just be points 1), 2), 4) the other ones are fine.
> 
> ### Requirements
> * [x]  I have reviewed the community membership guidelines in [`community-roles.md`](https://github.com/fluxcd/community/blob/main/community-roles.md#community-member)
> * [x]  I have subscribed to the cncf-flux-dev e-mail list https://lists.cncf.io/g/cncf-flux-dev/join
> * [x]  I am actively contributing to 1 or more `fluxcd` GitHub org repos (eg. Flux, Flagger)
> * [x]  I have enabled 2FA in GitHub
> * [x]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
> * [x]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Done

**Comment by dholbach** [comment]
Dear @fluxcd/core-maintainers please take a look.

**Comment by hiddeco** [comment]
@Arhell you should have an invite. Welcome!

**Comment by makkes** [comment]
+1 from me as a rep of the core maintainers. Thanks for your ongoing contributions @Arhell.

**Comment by pjbgf** [comment]
+1 from me. Welcome onboard @Arhell and thank you for all your effort so far! :bow:
