### ISSUE TITLE
Get a CNCF sub-account for ECR Public

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#212]
Ref:

- https://cloud-native.slack.com/archives/C01A402P0R2/p1654190336355629
- https://docs.google.com/document/d/1l_M0om0qUEN_NNiGgpqJ2tvsF2iioHkaARDeh6b70B0/edit#heading=h.5cq7ghee7utj

Not sure if https://github.com/aws/containers-roadmap/issues/1262 needs to be resolved beforehand.

Paging @chris-short @scottrigby @jaypipes

**Comment by stefanprodan** [comment]
We use buildkit to produce multi-arch images that are signed with cosign and pushed to GitHub Container Registry and Docker Hub. To reduce the cost the traffic cost for Flux users that are running their clusters on AWS, we would like to publish Flux and Flagger official images to ECR Public.

These are the images we would like to publish from our GitHub Actions release workflow:

- `public.ecr.aws/fluxcd/flux-cli`
- `public.ecr.aws/fluxcd/source-controller`
- `public.ecr.aws/fluxcd/kustomize-controller`
- `public.ecr.aws/fluxcd/helm-controller`
- `public.ecr.aws/fluxcd/notification-controller`
- `public.ecr.aws/fluxcd/image-reflector-controller`
- `public.ecr.aws/fluxcd/image-automation-controller`
- `public.ecr.aws/fluxcd/flagger`
- `public.ecr.aws/fluxcd/flagger-loadtester`

**Comment by jaypipes** [comment]
@stefanprodan ahoy there :) Do you want to *migrate* Flux's image publication to ECR Public? Or are you wanting to just *mirror* images that are also hosted elsewhere (dockerhub, GH container registry, etc) to a location where Flux users can pull image contents for free when they are in an AWS region?

**Comment by stefanprodan** [comment]
Hey @jaypipes we want to mirror the images and their consign signatures to ECR Public. If this is possible on the AWS side without us having to modify our release pipeline, then I would opt for that. If not, I'm ok with adding ECR login and push actions to all our workflows.

**Comment by jaypipes** [comment]
> Hey @jaypipes we want to mirror the images and their consign signatures to ECR Public. If this is possible on the AWS side without us having to modify our release pipeline, then I would opt for that. If not, I'm ok with adding ECR login and push actions to all our workflows.

@stefanprodan OK. Just wanted to check with you that you're OK with Flux users having to specify a different ECR Public image URI to take advantage of these mirrored images. It's not like it's transparent mirroring where there is a single metadata registry and only the image blobs/layers are mirrored (i.e. what we are doing for registry.k8s.io/k8s.gcr.io).

I can work with CNCF admins to create an AWS subaccount in the CNCF AWS Organization and an IAM role that has permission to push to ECR Public.

**Comment by stefanprodan** [comment]
@jaypipes during installation, a Flux user can chose from which registry to pull the images. After we get the images on Public ECR, AWS users can do:

```
flux bootstrap git \
--url=ssh://git@example.com/repository.git \
--registry=public.ecr.aws/fluxcd
``` 

> I can work with CNCF admins to create an AWS subaccount in the CNCF AWS Organization and an IAM role that has permission to push to ECR Public.

Thank you! We would really like to push to `public.ecr.aws/fluxcd`, I guess **fluxcd** is not taken.

**Comment by jaypipes** [comment]
> @jaypipes during installation, a Flux user can chose from which registry to pull the images. After we get the images on Public ECR, AWS users can do:
> 
> ```
> flux bootstrap git \
> --url=ssh://git@example.com/repository.git \
> --registry=public.ecr.aws/fluxcd
> ```

Ah, OK. :+1: 

> > I can work with CNCF admins to create an AWS subaccount in the CNCF AWS Organization and an IAM role that has permission to push to ECR Public.
> 
> Thank you! We would really like to push to `public.ecr.aws/fluxcd`, I guess **fluxcd** is not taken.

Yeah, the ECR Public registry "alias" is what you are referring to there. I will talk to the ECR Public team to reserve this alias as soon as we have the AWS accounts set up. I'll ping you on Slack when I get this done.

**Comment by stefanprodan** [comment]
@jaypipes any news on this?

**Comment by jaypipes** [comment]
> @jaypipes any news on this?

@stefanprodan really sorry for the delay. I have created the FluxCD Organization Unit under the main CNCF Organization and created a FluxCD Infra AWS account under that FluxCD Organization Unit.

I have also created a public registry and requested the `public.ecr.aws/fluxcd` alias for that registry. In the meantime, the default auto-generated registry alias is `n3q7y2u8`: https://gallery.ecr.aws/n3q7y2u8

I will ping you private Slack about setting up IAM users that you can use to push to this registry.

**Comment by kingdonb** [comment]
I'm just doing some housekeeping. Did we manage to land public ECR or is this issue still outstanding?

I see from fluxcd/source-controller#893 that it was reverted and something failed. (Should we keep the issue open?)

**Comment by kingdonb** [comment]
🏆
