### ISSUE TITLE
Revisit use of keybase

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#214]
fixes #33 

@scottrigby said in our Graduation DD Doc:

> Yes, 1password now for secure credential and info sharing. Keybase had one other intended value for the project - a vendor-independent private/secure chat for the Flux team, whenever this becomes necessary. We now have a private cncf slack #flux-maintainers channel for this, but that excludes non-maintainer Flux team members (like those who work on planning and coordinating community things who are not actually maintainers. For example, planning Flux graduation things).

> Ultimately though it's up to the project team whether or not we want to use keybase for this. So far it's very quiet. Right now I see it as a tool with good potential that we're not really using. A perhaps better approach to including important non-maintainer people in private discussions would be to make these key people official Flux maintainers as well (in the community repo, etc), and officially retire Keybase.

**Comment by scottrigby** [comment]
@stefanprodan this sounds right to me. I just wasn't sure if anyone still wanted to see use Keybase for that, but I agree with you in this 100%. Keybase multiple proofs ensure a very high level of trust people are who they say they are

**Comment by scottrigby** [comment]
For the other part of that snippet Daniel (thanks for posting into an issue by the way), perhaps it's time to nominate a few folks to join the existing community maintainers team. Flor example Tamao. So The work they're already doing for flux community can be a bit more officially recognized

**Comment by dholbach** [comment]
Note also #33.

I had a look around and we don't document our use of Keybase (apart from https://fluxcd.io/security/#security-team) anywhere.

My suggestion would be to document the security team in `community-roles.md` and `PROCESS.md`, where we define

- Scope of the Security Team (prerequisite to be Core Maintainer?)
- Process for how to be voted into it (vote from Core Maintainers?)
- The resources the Security Team members have access to

I realise that the solution is a bit more than what we tried to solve in this issue (and #33), but it should bring a bit more clarity in general.

Afterwards we can remove all Keybase teams to avoid confusion?

**Comment by scottrigby** [comment]
I agree, and we can just decommission the other teams 👌

**Comment by pjbgf** [comment]
I like the idea of using Keybase for discussing any new security reports and/or coordinating security work amongst the security team.

The vulnerability disclosure process must be as easy and straightforward as possible, so documenting it as one way for security researchers/enthusiasts to contact the Flux Security team is great. But it should not be the only way, after all some folks may way to report issues whilst keeping their anonymity.

**Comment by scottrigby** [comment]
Update: `fluxcd` keybase team still exists, as it's needed for the subteam `fluxcd.security`.
Just deleted `fluxcd.community`. Note there was one encrypted file `twitter.saltpack`, which is fine because the login - along with 2fa - is now in 1password, see https://github.com/fluxcd/community/issues/41#issuecomment-1203094754.

Now that this is done, we can auto-close this issue from #221 once merged. I will add autoclose keyword to description.
