### ISSUE TITLE
Welcome committee for new contributors

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#228]
An idea I would love to work on myself is: **a welcome committee**. Maybe we could use a fixed time in the Flux Dev meetings to take a look at who contributed PRs recently and make sure we invite them to Dev meeting, our Slack and generally make sure they have everything they need.

A small script like

```bash
for repo in $(gh api -H "Accept: application/vnd.github+json" /orgs/fluxcd/repos | jq '.[].full_name' | cut -d'"' -f2); do \
    gh pr list -s all -L 1000 -S 'created:>2022-08-01' \
        -R $repo --json url,title,author,state \
        --template '{{range .}}{{tablerow .author.login .state .url .title}}{{end}}'; \
done | sort
```

could be helpful for that. The script above is just a little bit of toying around on my part - and just to illustrate what we could do.

_Originally posted by @dholbach in https://github.com/fluxcd/community/issues/227#issuecomment-1224043373_

**Comment by dholbach** [comment]
Right now I'm looking into writing a small script, which updates a spreadsheet / csv file / ... and stores info like

>  who, repo, when, pull_id, pull_state

The idea being that we could use this info over time to give us info like

- PRs from new contributors since last week
- folks with >= 10 PRs since last time

We could over time make it so, that we have a GH Action which files a weekly or monthly issue, so we know who to reach out to.

Does anyone else have ideas or use cases this should cover?

**Comment by dholbach** [comment]
Thanks @kingdonb and @pjbgf  (ad others) for your ideas so far!

**Comment by kingdonb** [comment]
🏆
