### ISSUE TITLE
Monthly "How to start with Flux development" session

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#229]
What also came up in a discussion was to e.g. steal one of the Bug Scrub sessions a month and turn it into a "How to start with Flux development" session.

_Originally posted by @dholbach in https://github.com/fluxcd/community/issues/227#issuecomment-1224227589_

**Comment by dholbach** [comment]
AFAICT @stefanprodan @kingdonb @pjbgf seemed interested.

**Comment by kingdonb** [comment]
🏆
