### ISSUE TITLE
Make it easier for new contributors to find tasks

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#231]
Based on a chat with @makkes, I created a board view for new contributors to find items that are waiting for contributors.
We could share this profusely and see whether it lowers the entry bar to first contributions.

To add issues into that specific board view, they need to be labelled `help wanted` and added into the [Maintainers' Focus](https://github.com/orgs/fluxcd/projects/6/views/16) project.

_Originally posted by @pjbgf in https://github.com/fluxcd/community/issues/227#issuecomment-1225835301_

- [ ] Let's add to https://fluxcd.io/docs/contributing/flux/
- [ ] Let's mention and pin in Slack
- [ ] Let's add to [monthly update template](https://docs.google.com/document/d/1sET7smGd5Za-76Ywwhd-mh-dAyaZDlZ0GZ-oD3qnviU/edit#)
- [ ] Mention in next Flux Dev call - explain to maintainers how to use this
- [ ] ...

**Comment by dholbach** [comment]
cc @makkes @pjbgf

**Comment by kingdonb** [comment]
🏆
