### ISSUE TITLE
REQUEST: New membership for @stealthybox

### ISSUE THREAD

**Issue by stealthybox** [fluxcd/community#234]
### GitHub Username
@stealthybox

### Requirements
- [x] I have reviewed the community membership guidelines in [community-roles.md](community-roles.md)
- [x] I have subscribed to the cncf-flux-dev e-mail list [https://lists.cncf.io/g/cncf-flux-dev/join](https://lists.cncf.io/g/cncf-flux-dev/join)
- [x] I am actively contributing to 1 or more `fluxcd` GitHub org repos (eg. Flux, Flagger)
- [x] I have enabled 2FA in GitHub
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dholbach
- @phillebaba

### List of contributions to the Flux project
- PRs reviewed / authored:
    - https://github.com/fluxcd/flux2/pull/2347
    - https://github.com/fluxcd/flux2/pull/1469
    - https://github.com/fluxcd/website/pull/251
    - https://github.com/fluxcd/flux2/pull/1297
    - https://github.com/fluxcd/flux2/pull/1067
    - https://github.com/fluxcd/flux2/pull/1064
    - https://github.com/fluxcd/flux2/pull/1034
    - https://github.com/fluxcd/flux2/pull/1027
    - https://github.com/fluxcd/flux2/pull/966
    - https://github.com/fluxcd/flux2/pull/877
    - https://github.com/fluxcd/flux2/pull/582
    - https://github.com/fluxcd/kustomize-controller/pull/135
    - https://github.com/fluxcd/flux2/pull/235
    - https://github.com/fluxcd/flagger/pull/671
    - https://github.com/fluxcd/flagger/pull/663
    - https://github.com/fluxcd/flagger/pull/509
    - https://github.com/fluxcd/flux/pull/2334
- Discussions involved in & Issues responded to:
    - https://github.com/fluxcd/kustomize-controller/issues/352
    - https://github.com/fluxcd/terraform-provider-flux/issues/128
    - https://github.com/fluxcd/source-controller/issues/322
    - https://github.com/fluxcd/flux2/issues/1165
    - https://github.com/fluxcd/kustomize-controller/issues/305
    - https://github.com/fluxcd/flux2/issues/1127
    - https://github.com/fluxcd/flux2/issues/1126
    - https://github.com/fluxcd/flux2/issues/1125
    - https://github.com/fluxcd/kustomize-controller/issues/98
    - https://github.com/fluxcd/flagger/issues/510
    - https://github.com/fluxcd/flux/issues/2523
- Flux subprojects I am involved with (Flagger, Flux, Controllers):
    - flagger
    - flux
    - flux2
    - kustomize-controller
    - source-controller
    - terraform-provider-flux
    - website

**Comment by dholbach** [comment]
I'm very very happy to sponsor!

**Comment by stefanprodan** [comment]
Yey! Thanks Leigh for all your contributions

**Comment by phillebaba** [comment]
Great to have you back!

**Comment by dholbach** [comment]
Hey hello @fluxcd/org-admins we have a new project member! 🤩

**Comment by makkes** [comment]
Woohoo, welcome @stealthybox!

**Comment by stefanprodan** [comment]
Invitation sent

**Comment by stealthybox** [comment]
thank you friends ✨
this project is close to my heart, and I look forward to how Flux will continue to grow and serve new practitioners
