### ISSUE TITLE
New Membership for @rashedkvm

### ISSUE THREAD

**Issue by rashedkvm** [fluxcd/community#239]
### GitHub Username
@rashedkvm

### Requirements
- [x] I have reviewed the community membership guidelines in [community-roles.md](community-roles.md)
- [x] I have subscribed to the cncf-flux-dev e-mail list [https://lists.cncf.io/g/cncf-flux-dev/join](https://lists.cncf.io/g/cncf-flux-dev/join)
- [x] I am actively contributing to 1 or more `fluxcd` GitHub org repos (eg. Flux, Flagger)
- [x] I have enabled 2FA in GitHub
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @stefanprodan 
- @stealthybox

### List of contributions to the Flux project
- PRs reviewed / authored
  - https://github.com/fluxcd/source-controller/pull/788
  - https://github.com/fluxcd/image-reflector-controller/pull/252
- Discussions involved in & Issues responded to
  - https://github.com/fluxcd/flux2/discussions/3066
- Flux subprojects I am involved with (Flagger, Flux, Controllers)
  - Source Controller
  - Image-Reflector-Controller

**Comment by dholbach** [comment]
With #243 merged, this should now be easier.

**Comment by stealthybox** [comment]
+1
Thank you for your contributions to the OCI features @rashedkvm

**Comment by stefanprodan** [comment]
+1 from me, thanks @rashedkvm for all your contributions

**Comment by dholbach** [comment]
@fluxcd/org-admins Can @rashedkvm please be added as Flux Project Member?

**Comment by dholbach** [comment]
According to @hiddeco you should have an invitation now to be a Flux Project Member. Congratulations and welcome to the team!
