### ISSUE TITLE
Add featured talks section to readme

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/community#24]
Move the talks section from /toolkit and /flux to this repo.

**Comment by dholbach** [comment]
Now that we have https://fluxcd.io/community/ I feel we could move the talks info - the process for changing this would be simply to update the README in `/f/community` ... WDYT @mewzherder @staceypotter @somtochiama @scottrigby @stefanprodan and everyone else?

**Comment by staceypotter** [comment]
SGTM
