### ISSUE TITLE
REQUEST: New membership for @developer-guy

### ISSUE THREAD

**Issue by developer-guy** [fluxcd/community#242]
### GitHub Username
(Trendyol) developer-guy 

### Requirements
- [x] I have reviewed the community membership guidelines in [community-roles.md](community-roles.md)
- [x] I have subscribed to the cncf-flux-dev e-mail list [https://lists.cncf.io/g/cncf-flux-dev/join](https://lists.cncf.io/g/cncf-flux-dev/join)
- [x] I am actively contributing to 1 or more `fluxcd` GitHub org repos (eg. Flux, Flagger)
- [x] I have enabled 2FA in GitHub
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- (Weaveworks) @stefanprodan 
- (XenitAB) @phillebaba 

### List of contributions to the Flux project
- PRs reviewed/authored
	* https://github.com/fluxcd/source-controller/issues/863
- Blog Posts
	* https://fluxcd.io/blog/2022/08/manage-kyverno-policies-as-ocirepositories/
- Discussions involved in & Issues responded to
	* None
- Flux subprojects I am involved with (Flagger, Flux, Controllers)
	* Flux

kindly ping @dholbach

**Comment by stefanprodan** [comment]
+1 from me, looking forward to more OCI awesomeness 😄

**Comment by phillebaba** [comment]
+1 from me

**Comment by dholbach** [comment]
@fluxcd/org-admins Can @developer-guy please be added as Flux Project Member?

**Comment by dholbach** [comment]
According to @hiddeco you should have an invitation now to be a Flux Project Member. Congratulations and welcome to the team!
