### ISSUE TITLE
Update CNCF Landscape Summary

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#278]
Update https://landscape.cncf.io/summary entry for Flux, in particular [these](https://github.com/cncf/landscape/blob/master/readme_summary.md#fields-to-be-populated-by-project-owners):

**Target Users:**
Who is this project for? Who'll be using it? Developers, SRE/DevOps Engineers, Architects?
**Tags:**
Add tags that describe your project's properties. Please focus on technical features. The goal is for the user to differentiate and compare projects on a high level. Tags will allow them to infer project features, qualities, and properties.
Example: KubeEdge, Akri, OpenYurt, and SuperEdge will likely all share the Edge tag indicating that they relate to the network edge. OpenYurt and SuperEdge may also share the IoT tag, while KubeEdge and Akri won't. Metal3-io’s tags might show it to be the only project dealing with baremetal and provisioning.
**Use case:**
Focus on the technical problem your project solves. Why would someone need it? What technical pain points does it address? Be brief and limit your description to 500 characters.
**Business use:**
Comment on your project's business use case. How would it bring value to an organization? Does it reduce risk of some type (e.g., regulatory, reputational), or increase responsiveness to customer demand? Does it increase security in a way that reduces business support costs? What is the business problem your project is trying to solve? Be brief and limit your description to 500 characters.
**Release cadence:**
How often do you release a new version?
**Integrations:**
What does it integrate with?
**Overview video:**
Optional: 5 min product pitch. Same thing as above, but delivered in video format.

**Comment by dholbach** [comment]
- Release cadence: Refer to [FAQ entry](https://fluxcd.io/flux/faq/#where-can-i-find-information-on-how-long-versions-are-supported-and-how-often-to-expect-releases) regarding minor releases: ".. current release cadence of at least once per month to continue."

**Comment by dholbach** [comment]
- Target users: SREs, DevOps & Platform Engineers, Architects, Developers
- Integrations:
  - Flux: all standard Cloud Native, Git provider and observability tooling
  - Flagger: Gateway API + standard service meshes and ingress controllers
- Tags: OCI, container, security, gitops, Kubernetes, Helm, Observability, Software Supply Chain, Policy, CICD, Multi-Tenancy, API Gateway

**Comment by dholbach** [comment]
- Use case: Flux is a tool for keeping Kubernetes clusters in sync with sources of configuration (like Git repositories and OCI artifacts), and automating updates to configuration when there is new code to deploy. Flux is built from the ground up to use Kubernetes' API extension system, and to integrate with Prometheus and other core components of the Kubernetes ecosystem. Flux supports multi-tenancy and support for syncing an arbitrary number of Git repositories, among other long-requested features.

**Comment by dholbach** [comment]
cc @staceypotter @vanessaabankwah

**Comment by dholbach** [comment]
- business use: GitOps is the natural evolution of configuration as code. Businesses moving to Flux can deal with infrastructure at scale more easily, and allow their developers to focus on code, not on deployment problems. With its vast ecosystem of Flux integrations and being integrated into cloud offerings everywhere, adopting Flux can be adopted in virtually every setup.

**Comment by dholbach** [comment]
The only bit missing is the 5 min project pitch video.

**Comment by dholbach** [comment]
This is done and updated on https://landscape.cncf.io/summary now.

@vanessaabankwah (and @staceypotter) wanted to look into finding a good Flux project pitch video.

**Comment by kingdonb** [comment]
Linking to #91 and closing, the pitch video was mentioned as part of that. We don't have anyone working on this right now. Volunteers needed.
