### ISSUE TITLE
Add Scott to CNCF Service Desk

### ISSUE THREAD

**Issue by scottrigby** [fluxcd/community#28]
As part of https://github.com/fluxcd/community/pull/21 am I able to be added to ServiceDesk, to tag-team on things like https://github.com/fluxcd/community/issues/26#issuecomment-720577095 as needed?

I believe the current iteration of the governance says this is a decision for @fluxcd/oversight-committee

**Comment by dholbach** [comment]
@squaremo is in the process of talking to CNCF about updating the maintainers list. :pray:

**Comment by dholbach** [comment]
Looks like this is resolved. Let's see if we can get a Zoom set up.
