### ISSUE TITLE
Add Michael Fornaro as Project Member

### ISSUE THREAD

**Issue by xUnholy** [fluxcd/community#289]
### Requirements
- [x] I have reviewed the community membership guidelines in [community-roles.md](community-roles.md)
- [x] I have subscribed to the cncf-flux-dev e-mail list [https://lists.cncf.io/g/cncf-flux-dev/join](https://lists.cncf.io/g/cncf-flux-dev/join)
- [x] I am actively contributing to 1 or more `fluxcd` GitHub org repos (eg. Flux, Flagger)
- [x] I have enabled 2FA in GitHub
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @kingdonb 
- @staceypotter 

List of contributions to the Flux project: 
- https://github.com/search?q=org%3Afluxcd+author%3Axunholy+&type=pullrequests
- Active in Slack #flux channels with over 400+ responses and threads, search filter `in:#flux with:@Michael Fornaro` 
- Active in Bug Scrub session; Looking to support an AEST timezone session in future.
- In-direct involvement through being a co-founder at [k8s@Home](https://github.com/k8s-at-home/) Github & [Discord](https://discord.gg/sTMX7Vh) where we heavily support FluxCD users.

**Comment by kingdonb** [comment]
I discussed this with Michael before submitting the application and I strongly support this

We're now working together to expand the Bug Scrub, the first AEST "bug scrub" session was last week. This is meant to include more time zones who would typically not be able to attend (AEST-centric scheduling would be more accessible to Eastern Europe, India, Southeast Asia, etc.)

+1 from me!

**Comment by staceypotter** [comment]
I have also been in communication with Michael and fully support his application to become a member! 👏🙌❤️

**Comment by dholbach** [comment]
That's great @xUnholy - it looks like you checked all the boxes for https://github.com/fluxcd/community/blob/main/PROCESS.md#applying-for-flux-membership :tada:

**Comment by pjbgf** [comment]
+1 from me, happy to see @xUnholy joining in the community! :rocket:

**Comment by hiddeco** [comment]
+1 from me as well.

**Comment by stefanprodan** [comment]
@xUnholy I've sent you an invitation to Flux org.
