### ISSUE TITLE
REQUEST: add new member @mewzherder

### ISSUE THREAD

**Issue by mewzherder** [fluxcd/community#294]
### GitHub Username
@mewzherder 

### Requirements
- [x] I have reviewed the community membership guidelines in [community-roles.md](community-roles.md)
- [x] I have subscribed to the cncf-flux-dev e-mail list [https://lists.cncf.io/g/cncf-flux-dev/join](https://lists.cncf.io/g/cncf-flux-dev/join)
- [x] I am actively contributing to 1 or more `fluxcd` GitHub org repos (eg. Flux, Flagger)
- [x] I have enabled 2FA in GitHub
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @stealthybox 
- @staceypotter 

### List of contributions to the Flux project
- PRs reviewed / authored
- [x] Discussions involved in & Issues responded to: Assisting the community primarily in Slack, setting up Flux community conversations with maintainers, assist Flux users to prepare for conference CFPs, etc.
- [x] build monthly, quarterly, and annual reports on Flux metrics across the board.
- [x] I manage the team and the activities by the team that are dedicated to Flux and Flagger's success.
- Flux subprojects I am involved with (Flagger, Flux, Controllers)

**Comment by makkes** [comment]
💯 Tamao has done so much for the Flux project, especially organizing GitOpsCon several times now. Happy to welcome you to the team

**Comment by staceypotter** [comment]
💯 +1's! Again, loooong overdue and you have my full support! 👏

**Comment by stealthybox** [comment]
+1
Tamao has done so much for the project over the years, and should absolutely be included as a project member

**Comment by mewzherder** [comment]
got it. thanks.
