### ISSUE TITLE
Add CII Badge

### ISSUE THREAD

**Issue by caniszczyk** [fluxcd/community#3]
https://bestpractices.coreinfrastructure.org/

**Comment by dholbach** [comment]
- [x] https://github.com/fluxcd/flux2/pull/1223
- [x] https://github.com/fluxcd/flagger/pull/877
- [ ] Helm Controller: 91% waiting on analysis bits which are already present in flux2 (https://bestpractices.coreinfrastructure.org/en/projects/4784)
- [ ] Source Controller: https://bestpractices.coreinfrastructure.org/en/projects/4786
