### ISSUE TITLE
New Membership for @matheuscscp

### ISSUE THREAD

**Issue by matheuscscp** [fluxcd/community#300]
# GitHub Username

@matheuscscp

# Requirements

* [x] I have reviewed the community membership guidelines in [community-roles.md](https://github.com/fluxcd/community/blob/main/community-roles.md)
* [x] I have subscribed to the cncf-flux-dev e-mail list https://lists.cncf.io/g/cncf-flux-dev/join
* [x] I am actively contributing to 1 or more fluxcd GitHub org repos (eg. Flux, Flagger)
* [x] I have enabled 2FA in GitHub
* [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
* [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

# Sponsors

* @stefanprodan 
* @hiddeco 
* @pjbgf 

# List of contributions to the Flux project

* PRs authored
  * https://github.com/fluxcd/flux2/pull/3696
  * https://github.com/fluxcd/flux2/pull/3833
  * https://github.com/fluxcd/pkg/pull/544
  * https://github.com/fluxcd/notification-controller/pull/515
  * https://github.com/fluxcd/notification-controller/pull/517
  * https://github.com/fluxcd/notification-controller/pull/519
  * https://github.com/fluxcd/notification-controller/pull/529
  * https://github.com/fluxcd/notification-controller/pull/530
* PRs reviewed
  * https://github.com/fluxcd/image-reflector-controller/pull/368
  * https://github.com/fluxcd/helm-controller/pull/692
  * https://github.com/fluxcd/notification-controller/pull/534
* Discussions involved in & Issues responded to
  * https://github.com/fluxcd/flux2/discussions/2312
  * https://github.com/fluxcd/image-reflector-controller/issues/370
  * https://github.com/fluxcd/flux2/issues/3270
  * https://github.com/fluxcd/helm-controller/issues/678
* Flux subprojects I am involved with
  * Mostly notification-controller by looking at the PRs so far, but I will be involved with any subproject somehow interfacing with the use cases of Arista Networks. This already spans over all the Flux controllers

**Comment by makkes** [comment]
+1

**Comment by makkes** [comment]
Can we get another sponsor here so that we adhere to our [defined process](https://github.com/fluxcd/community/blob/51dafa3416f227c5445a845e9be7e2b943087892/PROCESS.md#applying-for-flux-membership)?

> Sponsors must be from multiple companies to demonstrate integration across community

**Comment by stefanprodan** [comment]
Pinging @relu @pjbgf @stealthybox @phillebaba

**Comment by pjbgf** [comment]
+1

**Comment by relu** [comment]
+1

**Comment by phillebaba** [comment]
+1

**Comment by hiddeco** [comment]
With (near) unanimous support, I have send you an invite @matheuscscp. Once accepted, you can close this issue.

Welcome! :wave:

**Comment by matheuscscp** [comment]
Thanks @hiddeco! Is `PROJECT-MEMBERS.md` being kept up-to-date?

**Comment by hiddeco** [comment]
It should be.
