### ISSUE TITLE
Spelling Correction Needed in Documentation

### ISSUE THREAD

**Issue by zeed-w-beez** [fluxcd/community#322]
Dear Maintainers,

I hope this message finds you well. While browsing through the project documentation, I noticed a minor spelling error that might need your attention.

As shown in the screenshot, the word 'Cosgin' is used, which I believe should be 'Cosign'. This could potentially cause confusion for people trying to understand the concept or use the tool.
![image](https://github.com/fluxcd/community/assets/20834022/56ea97a5-fc48-48a4-a96b-2360f17037de)

I hope this helps improve the documentation. Thank you for your continuous work on this project.

Best Regards

**Comment by kingdonb** [comment]
Thank you for reporting this! 🥇 

Fixed in fluxcd/website#1761
