### ISSUE TITLE
keybase teams

### ISSUE THREAD

**Issue by scottrigby** [fluxcd/community#33]
## Need

While Flux communication strives for transparency, there are instances where certain teams need a secure channel or communication on specific things. One example is for reviewing and addressing security reports privately before a fix is found and it can be publicly disclosed. Another is assessing Code of Conduct violation reports. Most other things should be communicated about in public.

## Status

I have added a keybase team fluxcd, and invited flux maintainers. All maintainers should be welcome to join this. There are private sub-teams so far for flux.security and flux.oversight, and the correct people have been added to those.

**Comment by kingdonb** [comment]
I am not on the Keybase team. Is this still active?

**Comment by stefanprodan** [comment]
I can invite you, give me a ping on Keybase I'm `@stefnprodan` there.

**Comment by dholbach** [comment]
Are we using both Keybase and 1password?
