### ISSUE TITLE
Add Luke Mallon as Project Member

### ISSUE THREAD

**Issue by Nalum** [fluxcd/community#339]
### GitHub Username
@nalum

### Requirements
- [X] I have reviewed the community membership guidelines in [community-roles.md](https://github.com/fluxcd/community/blob/main/community-roles.md)
- [X] I have subscribed to the cncf-flux-dev e-mail list [https://lists.cncf.io/g/cncf-flux-dev/join](https://lists.cncf.io/g/cncf-flux-dev/join)
- [X] I am actively contributing to 1 or more `fluxcd` GitHub org repos (eg. Flux, Flagger)
- [X] I have enabled 2FA in GitHub
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @stefanprodan 
- @souleb 

### List of contributions to the Flux project
- PRs reviewed / authored
  - https://github.com/fluxcd/kustomize-controller/pull/1017
  - https://github.com/fluxcd/image-automation-controller/pull/284
  - https://github.com/fluxcd/image-automation-controller/pull/283
  - https://github.com/fluxcd/flux2/pull/2195
  - https://github.com/fluxcd/flux2/pull/2193
  - https://github.com/fluxcd/website/pull/654
  - https://github.com/fluxcd/website/pull/653
- Discussions involved in & Issues responded to
  - https://github.com/fluxcd/flux2/issues/3886
  - https://github.com/fluxcd/kustomize-controller/issues/982
  - https://github.com/fluxcd/website/issues/645
  - Blog Post: https://luke.mallon.ie/posts/2022-02/flux-with-kind-and-soft-serve/

**Comment by stefanprodan** [comment]
Big +1 from me, thanks Luke for all your contributions to Flux 🏅

**Comment by souleb** [comment]
I fully support @Nalum application to become a member! 👏

**Comment by aryan9600** [comment]
Huge +1 from me, welcome aboard @Nalum 🥳

**Comment by makkes** [comment]
Woohoo, so happy to have Luke on the team!

**Comment by stefanprodan** [comment]
@Nalum you should have an invite to join the org. Please open a PR on this repo and add yourself to this file https://github.com/fluxcd/community/blob/main/PROJECT-MEMBERS.md
