### ISSUE TITLE
Proposal for Flagger to join Flux project and CNCF

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/community#34]
The Flagger authors are requesting for Flagger to join the **fluxcd** org.

Flagger extends Flux functionality with progressive delivery strategies like Canary Releases, A/B Testing and Blue/Green and it was specifically designed for GitOps style delivery.

Since the inception of the GitOps Toolkit, it’s clear that fluxcd/ will become more of a family of GitOps related projects. The Flagger maintainers are looking forward to making use of the toolkit components and simplifying Flagger this way. Consolidating the code-bases and thinking in terms of a “Flux Family of Projects” and writing up the roadmap accordingly should benefit both communities as a whole.

Background information:

- Approval of Flagger maintainers (Stefan Prodan and Takeshi Yoneda)
- Approval from Weaveworks to transfer Flagger and its copyright to fluxcd org (and thus, CNCF) 
- Upcoming roadmap for Flagger includes [GitOps Toolkit integration](https://github.com/weaveworks/flagger#roadmap)
- License, dependencies and copyright review can be found [here](https://gist.github.com/dholbach/1047d5cfa2d8d59aeb88cdb8f68f75af)

We would like to present at one of the next Flux meetings and state our intent in more detail. We are looking forward to your questions and a good debate.

**Comment by monadic** [comment]
+1 great idea

**Comment by squaremo** [comment]
Flagger is a great fit for the Flux project. I'm :100: on board with this.

**Comment by mathetake** [comment]
As a maintainer, I am completely +1 :1st_place_medal:

**Comment by hiddeco** [comment]
+1 without any doubt

**Comment by scottrigby** [comment]
➕1️⃣
