### ISSUE TITLE
REQUEST: New membership for @mewzherder

### ISSUE THREAD

**Issue by mewzherder** [fluxcd/community#341]
GitHub Username
@mewzherder 

Requirements

- [ x ]  I have reviewed the community membership guidelines in community-roles.md
- [ x ]  I have subscribed to the cncf-flux-dev e-mail list https://lists.cncf.io/g/cncf-flux-dev/join
- [ x ]  I am actively contributing to 1 or more fluxcd GitHub org repos (eg. Flux, Flagger)
- [ x ]  I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ x ]  I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors
@kingdonb 
@makkes 

List of contributions to the Flux project
- Managed and supported team of Flux maintainers and Community Managers for project development, events, support, etc.
- Organize Flux community support by coordinating maintainer conversations.
- Maximize Flux and Flagger visibility at events through CFP coordination with maintainers, contributors, and users.
- Maximize Flux and Flagger visibility at events through Flux booth support: team coordination, project meeting planning and execution, booth hours, chop wood / carry water, etc.
- Maximize CNCF Marketing opportunities for the Flux project: coordinate webinars, live streams, meetups, blog post, work with the PR team, etc.
- Promote the Flux project through multiple relevant channels: CNCF, events, OSS communities, DX communities, etc.

**Comment by makkes** [comment]
+1 from me. There's no way not to have Tamao onboard going forward.

**Comment by souleb** [comment]
+1 from me too.

**Comment by kingdonb** [comment]
Strongly supportive, I think it's long past time we add this formal recognition of the contribution you've made @mewzherder !

+1

**Comment by scottrigby** [comment]
+1

Based on merit and past involvement, absolutely.

Will also make community-related project maintainer conversations much more direct 🙂

**Comment by kingdonb** [comment]
I see @stefanprodan is in support from his 👍 on the top issue, for our reference here is the process for applying for maintainer:

https://github.com/fluxcd/community/blob/main/PROCESS.md#applying-for-flux-maintainership

**Comment by stefanprodan** [comment]
@mewzherder you can now make your org membership public, to do so, go to https://github.com/orgs/fluxcd/people and select `Public` from the dropdown.

**Comment by stefanprodan** [comment]
@mewzherder you are now a maintainer of the community repo 🎉

**Comment by mewzherder** [comment]
@stefanprodan ok. I think it is set to public now. thx. ❤️

**Comment by mewzherder** [comment]
closed
