### ISSUE TITLE
Indicate interest in a GitOps working group

### ISSUE THREAD

**Issue by AloisReitbauer** [fluxcd/community#38]
Hey Flux team,

please indicate your interest in joining a working group on GitOps.

You can find the CNCF SIG App Delivery issue here: https://github.com/cncf/sig-app-delivery/issues/27

**Comment by todaywasawesome** [comment]
Speaking for Codefresh, we're very engaged here.

**Comment by csand-msft** [comment]
Microsoft Azure engaged and will join the GitOps working group

**Comment by stefanprodan** [comment]
As a member of @fluxcd/oversight-committee I support this initiative 💯

**Comment by dholbach** [comment]
As https://github.com/fluxcd/flux2/discussions/480 is resolved, I guess we can close this?
