### ISSUE TITLE
REQUEST: New membership for @swade1987

### ISSUE THREAD

**Issue by swade1987** [fluxcd/community#390]
**GitHub Username**
@swade1987

**Requirements**
- [x] I have reviewed the community membership guidelines in [community-roles.md](https://github.com/fluxcd/community/issues/community-roles.md)
- [x] I have subscribed to the cncf-flux-dev e-mail list https://lists.cncf.io/g/cncf-flux-dev/join
- [x] I am actively contributing to 1 or more fluxcd GitHub org repos (e.g. Flux, Flagger)
- [x] I have enabled 2FA in GitHub
- [x] I have two sponsors who meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

**Sponsors**
@stefanprodan 
@darkowlzz 

**List of contributions to the Flux project**

- https://github.com/fluxcd/terraform-provider-flux/pull/616
- https://github.com/fluxcd/terraform-provider-flux/pull/613
- https://github.com/fluxcd/terraform-provider-flux/pull/610
- Performer of several talks on Flux (see https://github.com/swade1987/public-speaking)
- Spoke at GitOpsDays (https://www.youtube.com/watch?v=M-3_cHxtBFs / https://www.youtube.com/watch?v=J79KStAjjGg) 

**Additional context**
My journey with Flux began with its first version. Since then, I've had the privilege of implementing v1 and v2 across various organizations, from financial services to security startups. This experience has not only deepened my understanding of Flux's pivotal role in automating and managing Kubernetes configurations but also allowed me to witness firsthand the transformative impact it has on streamlining deployment workflows and enhancing operational efficiencies.

As someone who has navigated the evolution of Flux and contributed to its application in various professional contexts, I am keenly aware of the potential and challenges that come with managing infrastructure as code, particularly in environments as dynamic and demanding as financial services and security. It is this rich backdrop of experiences and a forward-looking vision that I wish to bring to the [terraform-provider-flux](https://github.com/fluxcd/terraform-provider-flux) repository.

I aim to contribute actively to its growth and sustainability, ensuring that it continues to meet the needs of its users with reliability and innovation. By joining the Flux community organization on GitHub, I want to leverage my background to foster enhancements, drive adoption, and support the community in navigating the complexities of modern infrastructure management with Flux.

**Comment by stefanprodan** [comment]
Thanks @swade1987 for helping with the Flux TF provider 🏅

**Comment by swade1987** [comment]
Created https://github.com/fluxcd/community/pull/392

**Comment by souleb** [comment]
+1 from me.

**Comment by kingdonb** [comment]
Approved and merged in #392 🏆
