### ISSUE TITLE
REQUEST: New membership for @dipti-pai

### ISSUE THREAD

**Issue by dipti-pai** [fluxcd/community#409]
### GitHub username

dipti-pai

### Requirements

- [X] I have reviewed the community membership guidelines in https://github.com/fluxcd/community/issues/community-roles.md
- [X] I have subscribed to the cncf-flux-dev e-mail list https://lists.cncf.io/g/cncf-flux-dev/join
- [X] I am actively contributing to 1 or more fluxcd GitHub org repos (e.g. Flux, Flagger)
- [X] I have enabled 2FA in GitHub
- [X] I have two sponsors who meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

@stefanprodan 
@darkowlzz 

### List of contributions to the Flux project

Features

1. https://github.com/fluxcd/flux2/pull/4806
2. https://github.com/fluxcd/pkg/pull/789
3. https://github.com/fluxcd/source-controller/pull/1591
4. https://github.com/fluxcd/image-automation-controller/pull/747
5. https://github.com/fluxcd/flux2/pull/4986

Test enhancements

1. https://github.com/fluxcd/test-infra/pull/44
2. https://github.com/fluxcd/pkg/pull/793
3. https://github.com/fluxcd/image-automation-controller/pull/745

Documentation 

1. https://github.com/fluxcd/website/pull/1944
2. https://github.com/fluxcd/image-reflector-controller/pull/557
3. https://github.com/fluxcd/kustomize-controller/pull/1152
		
Issues 

1. https://github.com/fluxcd/flux2/issues/4726
2. https://github.com/fluxcd/flux2/discussions/4987

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
+1 from me 👍

**Comment by matheuscscp** [comment]
+1 from me :+1:

**Comment by stefanprodan** [comment]
@dipti-pai you should have an invitation to join the FluxCD org. After you accept, please make your membership public and open a PR to add yourself to this file https://github.com/fluxcd/community/blob/main/PROJECT-MEMBERS.md
