### ISSUE TITLE
Twitter account

### ISSUE THREAD

**Issue by scottrigby** [fluxcd/community#41]
- [x] Create https://twitter.com/fluxcd
- [x] Appeal suspended account
- [x] Add account credentials to `fluxcd.community` file share

## Status

- Account is up: [@fluxcd](https://twitter.com/fluxcd)
- Logo, description, and website is added. No posts yet. We could also use a header image, maybe of a kubecon talk or something.

See issue history for previous status.

**Comment by dholbach** [comment]
Let's add to https://github.com/fluxcd/community/blob/main/COMMUNITY.md#communications once it's back, and add account details to Keybase so the Comms team can use it?

**Comment by scottrigby** [comment]
Follow-up, credentials are now in fluxcd 1password. See #43
