### ISSUE TITLE
Add @matheuscscp to the Flux Security team

### ISSUE THREAD

**Issue by matheuscscp** [fluxcd/community#419]
I'd like to join the Flux Security team.

**Comment by pjbgf** [comment]
+1 from me.

This requires [unanimous votes](https://fluxcd.io/governance/#unanimity-decisions) with a quorum of at least 2/3 of [core maintainers](https://github.com/fluxcd/community/blob/main/CORE-MAINTAINERS).

**Comment by hiddeco** [comment]
+1 from me.

**Comment by stefanprodan** [comment]
+1 from me.

**Comment by makkes** [comment]
> Security Team members must use their access to the [oss-fuzz issues catalog](https://bugs.chromium.org/p/oss-fuzz/) to investigate issues raised from fuzz tests.

Please add yourself to https://github.com/google/oss-fuzz/blob/master/projects/fluxcd/project.yaml to be able to satisfy this requirement.

+1

**Comment by matheuscscp** [comment]
@makkes Done :ok_hand:

**Comment by stefanprodan** [comment]
+1 from me.

**Comment by relu** [comment]
+1

**Comment by matheuscscp** [comment]
Superseded by https://github.com/fluxcd/.github/pull/29
