### ISSUE TITLE
Unify contributing docs?

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#42]
We are starting to have diverging docs on how to contribute to Flux projects:

- https://github.com/fluxcd/flux/blob/master/CONTRIBUTING.md
- https://github.com/fluxcd/community/blob/main/CONTRIBUTING.md
- https://github.com/fluxcd/flux/blob/master/docs/contributing/get-started-developing.md

Do we want to unify these docs and keep in the community repo?

I realise that it might make sense to first figure out how we can pull in community docs into the fluxcd.io website and display them prominently before we replace docs elsewhere?

This might be a good opportunity to point out teams, initiatives and activities across projects more easily and keep things up to date this way.

**Comment by scottrigby** [comment]
And there's also https://github.com/fluxcd/flux2/blob/main/CONTRIBUTING.md.

What about keeping org-wide contributing info in `fluxcd/community` `CONTRIBUTING.md`, then other project repos (`fluxcd/flux2, `fluxcd/flagger`, etc) can each have a `CONTRIBUTING.md` point to the org-wide one, then just list any additional criteria below that pointer?

**Comment by dholbach** [comment]
It'd be good to link to it prominently on fluxcd.io as well.

**Comment by dholbach** [comment]
We have https://fluxcd.io/community/ as a starting point now.

**Comment by alisondy** [comment]
idea

contributing.md
```
you must sign your commits

see the contributor docs on the flux site on how to contribute to the flux project
```

contribute page on site

```
Contribute to Flux
Flux welcomes improvements from all contributors, new and experienced.

We gratefully welcome improvements to issues and documentation as well as to code.

Getting Started
Anyone can open an issue about documentation, or contribute a change with a pull request (PR) to Flux. You need to be comfortable with git and GitHub to work effectively in the Flux community

To prepare for your first contribution to Flux:

Read through and understand our contributing document
Read the Contribution overview to learn about the different ways to contribute to Flux
Check out good first issues in flux using this filter
Next steps
Learn how to develop Flux docs locally Learn how to write a feature proposal for flux

Get involved
Join our slack 
Join our mailing list 
Join our weekly meeting
```

**Comment by dholbach** [comment]
That sounds great https://fluxcd.io/contributing/ now comes from `/f/community`.

**Comment by dholbach** [comment]
Next up would be somebody having a pass at 
1. making sure that all content from other contributing docs made it safely to ^ this page
2. replacing "old docs" with links to the new one?

**Comment by dholbach** [comment]
Let's move the file to https://github.com/fluxcd/.github - see https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/ for an explanation.

**Comment by dholbach** [comment]
https://github.com/fluxcd/flux2/blob/main/CONTRIBUTING.md is different from https://fluxcd.io/contributing/

**Comment by dholbach** [comment]
For contributing to Flux, we use the file from `.github` now and import it into the website.

`flux2` still has a separate `CONTRIBUTING.md` that we should probably highlight somehow... or include? Maybe move some bits to `DEVELOPMENT.md` instead?
