### ISSUE TITLE
Create a repository template for new repositories

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/community#46]
Since Flux v2 our collection of repositories has been growing, and this will likely continue to happen.

To make the process of creating a repository more easy and aligned with what we have set out in our `GOVERNANCE.md`, we can create a [template repository](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) so that much of the manual labour we have to do now is automated, and the same for all repositories.

(Incomplete) list of things that should be included:

- `LICENSE`
- `DCO`
- `CODE_OF_CONDUCT.md`

**Comment by philoserf** [comment]
Just coming to the party.

**Comment by dholbach** [comment]
AFAICS we can moved all these files to `fluxcd/.github` now: https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/

**Comment by kingdonb** [comment]
🏆
