### ISSUE TITLE
Archive Flux v1 example repositories 

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/community#50]
With Flux v2 approaching GA, new users get confused of which examples to use.

I propose we update https://github.com/fluxcd/flux-get-started and https://github.com/fluxcd/flux-kustomize-example with:

> In preparation of Flux v2 GA this repository with Flux v1 examples has been archived. The Flux v2 equivalent of what is shown here can be found at [flux2-kustomize-helm-example](https://github.com/fluxcd/flux2-kustomize-helm-example).

And https://github.com/fluxcd/multi-tenancy with:

> In preparation of Flux v2 GA this repository with Flux v1 examples has been archived. The Flux v2 equivalent of what is shown here can be found at [flux2-multi-tenancy](https://github.com/fluxcd/flux2-multi-tenancy).

After the readme update, we could archive these repos.

**Comment by dholbach** [comment]
High five @hiddeco and @stefanprodan
