### ISSUE TITLE
Figure out youtube playlist access

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#62]
We use this [youtube playlist](https://www.youtube.com/playlist?list=PLbx4FZ4kOKntmgJqaT-iJ8tn4xat150yL) to add all Flux dev meeting recordings. I gave the collaboration link (to add yourself) to all Flux maintainers, currently only @scottrigby accepted the invitation, but it looks like only I can add to it.

Maybe this is https://support.google.com/youtube/thread/16543628?hl=en in disguise...?

**Comment by dholbach** [comment]
@alisondy and I are figuring out a Youtube channel: https://www.youtube.com/channel/UCoZxt-YMhGHb20ZkvcCc5KA

**Comment by dholbach** [comment]
The idea is to re-upload the meeting videos there. Once this is done, we'll update the documentation to point to the right place.

Give me a ping if you're maintainer and you would like to be added as having access.

**Comment by alisondy** [comment]
We should probably keep a list of 

Yt-admins in the community repos

**Comment by alisondy** [comment]
this will be addressed by documenting youtube infra, figuring out that process as part of #91

**Comment by kingdonb** [comment]
Not clear to me if this is still in progress, or how it looks when resolved. (If you DM me the invite I will accept it!)

**Comment by dholbach** [comment]
I wonder if we need to document this more and make sure everyone has access, or improve the process of uploading videos.

**Comment by dholbach** [comment]
Defined in https://github.com/fluxcd/community/blob/main/COMMUNITY.md#access-to-things now
