### ISSUE TITLE
Update "early" meeting time

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#68]
AFAICS there was no objections?

cc @kingdonb @scottrigby

**Comment by stefanprodan** [comment]
No objections raised at the last meeting, please update the time to +2h. Thanks @dholbach

**Comment by scottrigby** [comment]
This is done on the flux-dev list calendar. Requested through service desk to be mirrored on the shared cncf calendar. Let's keep this open until that ticket is closed. I'll update here when it is 🙂

**Comment by dholbach** [comment]
AFAICT it was updated. It's what Amye says on the ticket too.
