### ISSUE TITLE
branding

### ISSUE THREAD

**Issue by alisondy** [fluxcd/community#77]
consolidate our branding information in one doc,

have our logos live in the community site

**Comment by dholbach** [comment]
Right now we have lots of different colours:
- https://github.com/fluxcd/flux/blob/master/docs/_static/custom.css
- https://github.com/fluxcd/website/blob/main/assets/sass/style.sass
- https://branding.cncf.io/projects/flux/

**Comment by alisondy** [comment]
## Problem
Currently [the CNCF branding site][1] shows our branding for Flux project. Cannot be expanded as CNCF site only stores the images, colors for the project. Out of scope to include sub-projects.

## idea
Add a page to the flux website under fluxcd.io/branding

It should show the Logos and colors for
- the main project  - Flux
- the sub-projects - Flagger

### other notes

The page itself should pull images from /logos directory of each project repo, and perhaps have a colours.yaml file to specify project colors?

The page should template out onto page, for each project a card group for logos, a card group for colors.
Use the frontmatter in the page to define the cards similar to the docs landing page in docsy ver of website?

[1]: https://branding.cncf.io/projects/flux/

**Comment by dholbach** [comment]
Since https://github.com/cncf/artwork/issues/229 there's https://github.com/cncf/artwork/blob/master/examples/sandbox.md#flagger-logos now (should be incubation).

https://github.com/cncf/cncf-branding/issues/4 is not resolved though yet.

**Comment by dholbach** [comment]
I filed https://github.com/cncf/artwork/pull/249 and will propose a PR for https://github.com/cncf/cncf-branding/issues/4 as well.

**Comment by dholbach** [comment]
https://github.com/cncf/cncf-branding/pull/6

**Comment by dholbach** [comment]
I feel I updated all the places - anything else I've missed?

**Comment by dholbach** [comment]
Maybe worth closing. Please open a new issue if there's anything else we need to address.
