### ISSUE TITLE
Better Flux event/meeting reminders

### ISSUE THREAD

**Issue by scottrigby** [fluxcd/community#82]
## Problem

We don't currently have a manageable way for end users to stay up to date about Flux events/meetings.

1. As a stop-gap, we had enabled a setting on the [cncf-flux-dev calendar](https://lists.cncf.io/g/cncf-flux-dev/calendar): `Send Notice To Group When Event Happens (tagged with #cal-notice)`
    - Good idea but in retrospect this has become more annoying than helpful. Since the meetings are recurring and the notice rarely changes, it's just more one more thing for users to ignore, and would likely not notice when recurring meeting details change.
1. Flux events were added to the [shared CNCF calendar](http://cncf.io/calendar), which is a google cal for ALL CNCF PROJECT MEETINGS
    - Users may subscribe this calendar to their, but by doing so they subscribe to ALL CNCF project events, which floods the calendars of most users

## Proposed solutions

- [x] Now: Disable #cal-notice automated event reminders on cncf-flux-dev mailing list calendar
- [ ] Short term: Help users understand how to keep up to date with Flux meetings/events
    - Suggestion: add policy to f/community README [Communication section](https://github.com/fluxcd/community/blob/main/README.md#communication). Example:
        >Changes to the recurring Flux meetings will be announced in Slack, Twitter, and the cncf-flux-dev mailing list.
- [ ] Longer-term: Move events to [CNCF Community groups](https://community.cncf.io/)

**Comment by alisondy** [comment]
Maybe we could recreate the events on the mailing list and use add event and invite group - this would ensure the event would invite all people on the flux-dev mailing list

https://groups.io/helpcenter/membersmanual/1/working-with-calendars/adding-calendar-events

and ensure the events have send invite on join enabled

https://groups.io/helpcenter/ownersmanual/1/customizing-settings-for-premium-and-enterprise-features/calendar

This would make it so we can say

- Join the mailing list cncf-flux-dev and all the flux-dev meetings will be added to your calendar

**Comment by dholbach** [comment]
Is this any better now that we have e.g. https://fluxcd.io/#calendar?

**Comment by scottrigby** [comment]
I agree it is better. Thanks! That looks great 💯 

Also, fine points:
- point 1 (repeating reminders that don't show any difference and were very ignorable) was addressed a while ago 👍 
- point 2 (cncf calendar being too noisy for folks to subscribe to) was fixed by CNCF a while back, when the filter option was added
- The suggestion to move to community.cncf.io is something that I still think would be valuable, but not a high priority at the moment. I do think the community meetings you proposed could go there though, but we could make that call as we go and don't need this issue to stay open for that
