### ISSUE TITLE
Work to change any community uses of the phrase "Weaveworks Flux" to "(CNCF) Flux"

### ISSUE THREAD

**Issue by scottrigby** [fluxcd/community#87]
Various community blog posts, podcasts, etc prefix "Flux" with "Weaveworks". It should not be that way, now that Flux is a vendor-neutral CNCF project. [Example search](https://www.google.com/search?q=%22weaveworks+flux%22).

This is easy to accidentally overlook, since there are places where it makes sense to refer to both in the same sentence. For example "talking with folks from Weaveworks about Flux" is accurate and ok. But it's easy to shorten titles for marketing purposes, and the more examples out there like this the easier it is for new posts to follow in that vein.

This issue is to help consolidate efforts to fix existing incorrect references out in the wild.

**Comment by scottrigby** [comment]
Thanks @christianh814 and @chris-short for doing this from the Red Hat side 💯

**Comment by kingdonb** [comment]
I think this has been resolved
