### ISSUE TITLE
No TShirt in the CNCF Store

### ISSUE THREAD

**Issue by christianh814** [fluxcd/community#88]
There is no swag in the CNCF store for flux :(

https://store.cncf.io/search?q=flux

**Comment by dholbach** [comment]
Some discussion here: https://cloud-native.slack.com/archives/C01A402P0R2/p1616151185031700

@squaremo Do you know how where this stands?

**Comment by squaremo** [comment]
We decided on a colour (tan), but it turned out to be out of stock, so it's back with the suppliers in our second choice colour (light blue). Sorry for the delay, I know everyone is keen to be clothed head to toe in Flux kit :-P

**Comment by dholbach** [comment]
This is [resolved](https://store.cncf.io/search?q=flux) and [announced](https://fluxcd.io/blog/2021/05/june-2021-update/#the-cncf-flux-store-is-up) now.
