### ISSUE TITLE
Reupload Youtube Videos to Flux Channel

### ISSUE THREAD

**Issue by alisondy** [fluxcd/community#90]
As part of setting up Flux with a youtube channel, need to reupload all the meeting recordings

| Video | Uploaded? |
| - | - |
| 'Flux Dev Meeting - 2018-11-28.mp4' | ✅ |
| 'Flux Dev meeting - 2019-02-26.mp4' | ✅ |
| 'Flux Dev meeting - 2019-03-26.mp4' | ✅ |
| 'Flux Dev meeting - 2019-04-30.mp4' | ✅ |
| 'Flux Dev meeting - 2019-05-28.mp4' | ✅ |
| 'Flux Dev meeting - 2019-06-25.mp4' | ✅ |
| 'Flux Dev meeting - 2020-03-24.mp4' | ✅ |
| 'Flux Dev meeting - 2020-08-13.mp4' | ✅ |
| 'Flux Dev meeting - 2020-09-10.mp4' | ✅ |
| 'Flux Dev meeting - 2020-09-24.mp4' | ✅ |
| 'Flux Dev meeting - 2020-09-30.mp4' | ✅ |
| 'Flux Dev meeting - 2020-10-08.mp4' | ✅ |
| 'Flux Dev meeting - 2020-10-14.mp4' | ✅ |
| 'Flux Dev meeting - 2020-10-28.mp4' | ✅ |
| 'Flux Dev meeting - 2020-11-05.mp4' | ✅ |
| 'Flux Dev meeting - 2020-11-11.mp4' | ✅ |
| 'Flux Dev meeting - 2020-11-19.mp4' | ✅ |
| 'Flux Dev meeting - 2020-11-25.mp4' | ✅ |
| 'Flux Dev meeting - 2020-12-03.mp4' | ✅ |
| 'Flux Dev meeting - 2020-12-09.mp4' | ✅ |
| 'Flux Dev meeting - 2020-12-17.mp4' | ✅ |
| 'Flux Dev meeting - 2021-01-06.mp4' | ✅ |
| 'Flux Dev meeting - 2021-01-14.mp4' | ✅ |
| 'Flux Dev meeting - 2021-01-20.mp4' | ✅ |
| 'Flux Dev meeting - 2021-01-28.mp4' | ✅ |
| 'Flux Dev meeting - 2021-02-03.mp4' | ✅ |
| 'Flux Dev Meeting - 2021-02-11.mp4' | ✅ |
| 'Flux Dev meeting - 2021-02-17.mp4' | ✅ |
| 'Flux Dev meeting - 2021-02-25.mp4' | ✅ |
| 'Flux Dev meeting - 2021-03-03.mp4' | ✅ |
| 'Flux Dev meeting - 2021-03-17.mp4' | ✅ |
| 'Flux Dev meeting - 2021-03-25.mp4' | ✅ |
| 'Flux Dev meeting - 2021-03-31.mp4' | ✅ |
| 'Flux Dev meeting - 2021-04-08.mp4' | ✅ |
| 'Flux Dev meeting - 2021-04-14.mp4' | ✅ |

| Video | Uploaded? |
| - | - |
|GitOps Toolkit Feedback meeting - 2020-07-02.mp4| ✅ |
|GitOps Toolkit and Flux v2 - 2020-07-16.mp4| ✅ |
|GitOps Toolkit meeting - 2020-07-30.mp4| ✅ |

[ ] publish playlist
[ ] put it on front of channel

**Comment by stefanprodan** [comment]
@alisondy can you please create an image that says "Flux dev meeting" and set that as a thumbnail for all videos?

**Comment by alisondy** [comment]
![Flux Dev meeting - 2019-02-26](https://user-images.githubusercontent.com/19580905/114706972-95f0cd00-9d21-11eb-94a5-f09f31dd0d23.png)

wdyt?

furhter note

imagemagick command

 ``convert fluxmeetingthumbnail.png -gravity East -font ../Downloads/Montserrat/Montserrat-Regular.ttf -pointsize 70 -annotate 0 'Flux Dev meeting\n2019-02-26' 'Flux Dev meeting - 2019-02-26.png'``

**Comment by stefanprodan** [comment]
@alisondy looks great, but for the existing ones I think a generic thumbnail will be less work.

**Comment by alisondy** [comment]
all youtube videos up to date if someone would like to review and double check that would be sweet

**Comment by dholbach** [comment]
We should decommission the old youtube playlist and make sure we don't refer to it anywhere - then this issue can be closed?

Old: https://www.youtube.com/playlist?list=PLbx4FZ4kOKntmgJqaT-iJ8tn4xat150yL

**Comment by dholbach** [comment]
@alisondy I made the old youtube playlist 'unlisted' and added a description which points to the new playlist. Shall I delete the old videos?

**Comment by dholbach** [comment]
I uploaded the old youtube playlist and videos. I guess we can close the issue now.

Please open a new issue if there's anything else that we should fix.
