### ISSUE TITLE
Umbrella Issue - Setup Youtube Account

### ISSUE THREAD

**Issue by alisondy** [fluxcd/community#91]
This is an umbrella issue to track youtube migration
| Task | Issue Link |
| - | - |
| Reupload Videos | #90 |
| Create Cover Image for channel | #95 |
| Document Youtube Infra | |
| Create Youtube channel description | |
| Create Channel Intro Video | |
| Curate playlist for flux tutorials | |

Other notes
- the channel primary owner is currently daniel
- we might need some gsuite or something that is paid for by CNCF, to have an account contributors@fluxcd.io to own things like youtube channel, docs, forms
  - this probs belongs to some wider issue regarding community/contributor infrastructure

**Comment by dholbach** [comment]
Zoom is already done through CNCF.

**Comment by alisondy** [comment]
👀

**Comment by dholbach** [comment]
What's still missing here?

**Comment by kingdonb** [comment]
#95 would be nice as some Flux maintainers have asked to not be pictured on the thumbnail

I'm maintaining the channel now, which consists of uploading the Flux Dev Meeting recordings and adding the YouTube link to the agenda doc (and adding the link to the agenda doc to the YouTube description, and marking it as "not made for kids")

I'm going to close this unless anyone is planning to follow it up, I'll keep #95 open though
