### ISSUE TITLE
Update popular Flux pages to refer to flux2

### ISSUE THREAD

**Issue by dholbach** [fluxcd/community#94]
We should try to find popular guides, posts or pages which refer to Flux v1 and see if we can add a quick note at the top to refer to Flux v2. 

1. What would be a good paragraph we can paste at the top of these?
2. What are popular pages we would like to see changed?

**Comment by dholbach** [comment]
>     2. What are popular pages we would like to see changed?

I'd be happy to add to posts on <https://weave.works/blog>.

**Comment by kingdonb** [comment]
If I understand correctly this is also mainly about external sites that have made tutorials that are now out of date

(Like Okteto: https://okteto.com/blog/okteto-cloud-meets-gitops/)

We should be collecting the sites that we want to send an inquiry to here

**Comment by kingdonb** [comment]
Thanks for your work here Daniel, I'm closing out these issues on the fluxcd/community repo as they are stale.

🏆 👋
